my files

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,14 +1,23 @@
 #!/usr/bin/env bash
-# Configure Nginx so that its HTTP response contains a custom header
-# The name of the custom HTTP header must be `X-Served-By`
-# The value of the custom HTTP header must be the `hostname` of the server Nginx is running on
+# This script installs and configures Nginx to add a custom HTTP response header X-Served-By with the server hostname
 
-sudo apt-get update
-sudo apt-get -y install nginx
-sudo ufw enable
-sudo ufw allow 'Nginx HTTP'
-echo 'Hello World!' |sudo tee /var/www/html/index.html
+# Exit on error
+set -e
 
-custom_header="server_name _;\n\tadd_header X-Served-By \$HOSTNAME;"
-sudo sed -i "s|server_name _;|$custom_header|" /etc/nginx/sites-enabled/default
-sudo service nginx restart
+# Update and install nginx
+apt-get update -y
+apt-get install -y nginx
+
+# Replace the default index page
+echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
+
+# Get the server hostname
+HOSTNAME=$(hostname)
+
+# Insert the custom header into the default Nginx config
+# This ensures that each response has X-Served-By: <hostname>
+sed -i "/server_name _;/a \\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default
+
+# Restart nginx without systemctl
+service nginx restart
+
